components:
  schemas:
      Product:
          type: object
          properties:
              id:
                  type: integer
                  description: The product's unique id
              title:
                  type: string
                  description: The product's name
              description:
                  type: string
                  description: The description of the product
              code:
                  type: string
                  description: The product's unique code
              price:
                  type: integer
                  description: The product's price
              status:
                  type: boolean
                  description: The product's status
              stock:
                  type: integer
                  description: The product's current stock
              category:
                  type: string
                  description: The product's category
              thumbnail:
                  type: string
                  description: The path to the product's image
          required:
              - id
              - title
              - description
              - code
              - price
              - status
              - stock
              - category
              - thumbnail
          example:
              id: 1
              title: "Sugus Confitados"
              description: "Confites azucarados multifruta."
              code: "A1234"
              price: 240
              status: true
              stock: 24
              category: "Caramelos"
              thumbnail: "/img/thumbnails/sugus"
  requestBodies:
    createProduct:
      type: object
      properties:
        title:
          type: string
          description: The product's name
        description:
          type: string
          description: The description of the product
        code:
          type: string
          description: The product's unique code
        price:
          type: integer
          description: The product's price
        stock:
          type: integer
          description: The product's current stock
        category:
          type: string
          description: The product's category
        thumbnail:
          type: string
          description: The path to the product's image
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: The product's name
        description:
          type: string
          description: The description of the product
        code:
          type: string
          description: The product's unique code
        price:
          type: integer
          description: The product's price
        stock:
          type: integer
          description: The product's current stock
        category:
          type: string
          description: The product's category
        thumbnail:
          type: string
          description: The path to the product's image